#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:/Applications/gwt-mac-1.4.10/gwt-user.jar:/Applications/gwt-mac-1.4.10/gwt-dev-mac.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.google.code.apis.rest.RestDescribe/RestDescribe.html;
